
name: emergen_sync
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  shake: ^3.0.0
  url_launcher: ^6.3.2
  location: ^8.0.1
  go_router: ^17.0.0
  csv: ^6.0.0
  flutter_lints: ^6.0.0
  flutter_contacts: ^1.1.9+2
  flutter_settings_ui: ^3.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
